### ISSUE TITLE
m_cWnd behaviour difference

### ISSUE THREAD

**Issue by adeepkit01** [gnandita/-Implementation-of-TCP-Low-Priority-TCP--LP-in-ns-3#1]
There is a difference between the unit of congestion window in ns-3 and Linux, the Linux cWnd is in terms of MSS so cWnd = 1 implies 1 MSS but in ns-3 it is bytes, so here to make congestion window equal to 1 of Linux, it should be multiplied with segmentSize

**Comment by mohittahiliani** [comment]
@CharithaS - Did you take care of this issue?

**Comment by CharithaS** [comment]
Yes sir, we have taken care of this issue by communicating with Ankit.

**Comment by mohittahiliani** [comment]
@adeepkit01 - Close this if verified?

**Comment by adeepkit01** [comment]
closed
